# Generated by Django 3.0.3 on 2020-09-18 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200918_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 17, 45, 12, 484962, tzinfo=utc)),
        ),
    ]
