# Generated by Django 3.0.3 on 2020-09-19 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200919_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 10, 6, 50, 574231, tzinfo=utc)),
        ),
    ]
